package dailyoffice

import (
	"bufio"
	"compress/gzip"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/dodopok/estevao-api-go/internal/civil"
)

// TestCwPrayerDuringDayTable replays Reading::Cw2005EnPrayerDuringDayPsalmTable
// .reference_for over 800 days, every pattern, with and without a week number
// (testdata generated by the Rails implementation).
func TestCwPrayerDuringDayTable(t *testing.T) {
	f, err := os.Open("testdata/cw_prayer_during_day.tsv.gz")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		t.Fatal(err)
	}
	sc := bufio.NewScanner(gz)
	n := 0
	for sc.Scan() {
		cols := strings.Split(sc.Text(), "\t")
		d, _ := civil.ParseISO(cols[0])
		week, hasWeek := 0, cols[2] != "nil"
		if hasWeek {
			week, _ = strconv.Atoi(cols[2])
		}
		if got := CwPrayerDuringDayReference(d, cols[1], week, hasWeek); got != cols[3] {
			t.Fatalf("%v: got %q", cols, got)
		}
		n++
	}
	if n != 8000 {
		t.Fatalf("read %d rows", n)
	}
}
