// Command routecov maps every request of the differential suites onto the
// Rails route table and prints, per route, whether the Go server implements
// its endpoint and how many oracle comparisons exercise it (as Markdown).
//
//	go run ./cmd/routecov > docs/ROUTE_COVERAGE.md
package main

import (
	"fmt"
	"net/url"
	"os"
	"sort"
	"strings"

	"github.com/dodopok/estevao-api-go/internal/app"
	"github.com/dodopok/estevao-api-go/internal/web"
	"github.com/dodopok/estevao-api-go/test/diff"
	"github.com/dodopok/estevao-api-go/test/diff/suites"
)

type usage struct {
	requests int
	statuses map[string]bool
	suites   map[string]bool
}

func main() {
	router := web.NewRouter(web.RailsRoutes)
	endpoints := app.Endpoints()
	byEndpoint := map[string]*usage{}
	unrouted := 0
	record := func(suite string, r diff.Request) {
		method := r.Method
		if method == "" {
			method = "GET"
		}
		path := r.Path
		if u, err := url.Parse(path); err == nil {
			path = u.EscapedPath()
		}
		m, ok := router.Recognize(method, path)
		if !ok {
			unrouted++
			return
		}
		u := byEndpoint[m.Endpoint]
		if u == nil {
			u = &usage{statuses: map[string]bool{}, suites: map[string]bool{}}
			byEndpoint[m.Endpoint] = u
		}
		u.requests++
		u.suites[suite] = true
	}
	names := suites.Names()
	sort.Strings(names)
	for _, name := range names {
		if scenarios, ok := suites.Scenarios(name); ok {
			for _, s := range scenarios {
				for _, r := range s.Steps {
					record(name, r)
				}
			}
			continue
		}
		reqs, err := suites.Build(name)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		for _, r := range reqs {
			record(name, r)
		}
	}

	fmt.Println("# Route coverage")
	fmt.Println()
	fmt.Println("Generated by `go run ./cmd/routecov`: every Rails route (`rails routes`, in")
	fmt.Println("recognition order), whether the Go server implements its endpoint, and how")
	fmt.Println("many requests of the differential suites (`cmd/difftest`) reach it, compared")
	fmt.Println("against the Rails oracle. Requests that exercise error paths count too.")
	fmt.Println()
	fmt.Println("| # | Verb | Path | Endpoint | Go | Compared requests | Suites |")
	fmt.Println("|---|------|------|----------|----|------------------:|--------|")
	implemented, covered, seen := 0, 0, map[string]bool{}
	for i, r := range web.RailsRoutes {
		_, ok := endpoints[r.Endpoint]
		goCol := "yes"
		if !ok {
			goCol = "**no**"
		} else if !seen[r.Endpoint] {
			implemented++
		}
		n, suiteList := 0, ""
		if u := byEndpoint[r.Endpoint]; u != nil {
			n = u.requests
			var ss []string
			for s := range u.suites {
				ss = append(ss, s)
			}
			sort.Strings(ss)
			suiteList = strings.Join(ss, ", ")
			if !seen[r.Endpoint] {
				covered++
			}
		}
		count := fmt.Sprint(n)
		if n == 0 {
			count = "**0**"
		}
		if seen[r.Endpoint] {
			count, suiteList = "(same endpoint)", ""
		}
		seen[r.Endpoint] = true
		fmt.Printf("| %d | %s | `%s` | `%s` | %s | %s | %s |\n", i+1, r.Verb, strings.ReplaceAll(r.Spec, "|", "\\|"), r.Endpoint, goCol, count, suiteList)
	}
	fmt.Println()
	fmt.Printf("%d routes, %d distinct endpoints: %d implemented in Go, %d compared by at least one request. ",
		len(web.RailsRoutes), len(seen), implemented, covered)
	fmt.Printf("%d suite requests match no route (they test the 404 path).\n", unrouted)
}
