# Writes test/diff/fixtures/audio.sql: users with the daily_office_audio flag
# and a partial clip catalogue (about six in seven clips present) for the
# offices the audio difftest requests, plus two text customizations, one the
# stored clip satisfies and one it does not.
#   bin/rails runner tools/golden/audio_fixture.rb test/diff/fixtures/audio.sql
require "digest"

TARGETS = [
  [ "loc_2015", "nvi", %w[2026-04-05 2026-09-16 2026-12-24], %w[morning evening compline] ],
  [ "loc_2019", "nvi", %w[2026-04-05], %w[morning] ],
  [ "loc_1979_en", "kjv", %w[2026-04-05 2026-09-16], %w[morning evening] ],
  [ "loc_1662_en", "kjv", %w[2026-09-16], %w[morning] ],
  [ "loc_2015", "nvi", %w[2026-05-24], %w[compline], { family_rite: true } ]
].freeze

def q(v) = v.nil? ? "NULL" : "'#{v.to_s.gsub("'", "''")}'"

clips = {}
TARGETS.each do |code, bible, dates, offices, extra|
  language = PrayerBook.find_by(code:).language
  provider = Audio::Providers.current(language:)
  generator = Audio::ClipGenerator.new(provider:, storage: Object.new)
  dates.each do |date|
    offices.each do |office|
      prefs = { prayer_book_code: code, bible_version: bible }.merge(extra || {})
      result = DailyOfficeService.new(date: Date.parse(date), office_type: office, preferences: prefs).call
      Audio::OfficeWalker.each_line(result) do |entry|
        next unless Audio::SpeakableLine::SPOKEN.include?(entry.type) && entry.text.present?

        generator.segments_for(entry.text, line_type: entry.type, slug: entry.slug, verse_number: entry.verse_number).each do |s|
          key = Audio::ClipKey.for(provider:, normalized: s)
          clips[key] ||= [ s, entry.type, provider ]
        end
      end
    end
  end
end

present = clips.select { |key, _| Digest::SHA256.hexdigest(key).to_i(16) % 7 != 0 }
custom = present.first(2)
lines = []
lines << "-- Generated by tools/golden/audio_fixture.rb. Rows are tagged instructions_sha256 = 'difftest'."
lines << "DELETE FROM user_audio_usages WHERE user_id IN (SELECT id FROM users WHERE provider_uid LIKE 'difftest-au-%');"
lines << "DELETE FROM feature_flags WHERE user_id IN (SELECT id FROM users WHERE provider_uid LIKE 'difftest-au-%');"
lines << "DELETE FROM user_onboardings WHERE user_id IN (SELECT id FROM users WHERE provider_uid LIKE 'difftest-au-%');"
lines << "DELETE FROM users WHERE provider_uid LIKE 'difftest-au-%';"
lines << "DELETE FROM audio_clips WHERE instructions_sha256 = 'difftest';"
lines << "DELETE FROM audio_clip_customizations WHERE created_by = 'difftest';"
lines << ""
lines << "INSERT INTO users (provider_uid, email, name, preferences, premium_expires_at, current_streak, longest_streak, timezone, created_at, updated_at) VALUES"
lines << " ('difftest-au-pt', 'au-pt@example.com', 'Audio', '{\"prayer_book_code\":\"loc_2015\",\"bible_version\":\"nvi\"}', '2099-01-01', 2, 5, 'America/Sao_Paulo', now(), now()),"
lines << " ('difftest-au-en', 'au-en@example.com', 'Audio EN', '{\"prayer_book_code\":\"loc_1979_en\",\"bible_version\":\"kjv\"}', '2099-01-01', 0, 0, 'UTC', now(), now()),"
lines << " ('difftest-au-free', 'au-free@example.com', 'Audio Free', '{\"prayer_book_code\":\"loc_2015\",\"bible_version\":\"nvi\"}', NULL, 0, 0, 'UTC', now(), now());"
lines << "INSERT INTO user_onboardings (user_id, prayer_book_id, bible_version_id, mode, onboarding_completed, completed_at, preferences, created_at, updated_at)"
lines << "SELECT u.id, pb.id, bv.id, 'basic', TRUE, now(), '{}', now(), now() FROM users u"
lines << "JOIN prayer_books pb ON pb.code = u.preferences->>'prayer_book_code' JOIN bible_versions bv ON bv.code = u.preferences->>'bible_version'"
lines << "WHERE u.provider_uid LIKE 'difftest-au-%';"
lines << "INSERT INTO feature_flags (feature_key, target_type, user_id, enabled, created_at, updated_at)"
lines << "SELECT 'daily_office_audio', 'user', u.id, TRUE, now(), now() FROM users u WHERE u.provider_uid LIKE 'difftest-au-%';"
lines << ""
lines << "INSERT INTO audio_clips (key, filename, text, line_type, kind, provider, voice, model, speed, duration, character_count, language, instructions_sha256, custom_instructions_sha256, created_at, updated_at) VALUES"
rows = present.map do |key, (text, type, provider)|
  duration = (500 + Digest::SHA256.hexdigest("d#{key}").to_i(16) % 9000) / 1000.0
  custom_digest = key == custom.first&.first ? "difftest-match" : nil
  " (#{q(key)}, #{q("tts/#{provider.name}/#{key}.mp3")}, #{q(text)}, #{q(type)}, 'line', #{q(provider.name)}, #{q(provider.voice)}, " \
    "#{q(provider.model)}, #{provider.speed}, #{duration}, #{text.length}, #{q(provider.language)}, 'difftest', #{q(custom_digest)}, now(), now())"
end
lines << rows.join(",\n") + "\nON CONFLICT (key) DO NOTHING;"
lines << ""
lines << "INSERT INTO audio_clip_customizations (text_digest, text, instructions, instructions_sha256, provider, model, voice, language, status, created_by, created_at, updated_at) VALUES"
lines << custom.each_with_index.map { |(key, (text, _type, provider)), i|
  " (#{q(Audio::Customization.text_digest(text))}, #{q(text)}, 'difftest', #{q(i.zero? ? "difftest-match" : "difftest-other")}, " \
    "#{q(provider.name)}, #{q(provider.model)}, #{q(provider.voice)}, #{q(provider.language)}, 'active', 'difftest', now(), now())"
}.join(",\n") + ";"
File.write(ARGV.fetch(0), lines.join("\n") + "\n")
puts "#{clips.size} clips, #{present.size} catalogued"
