package activestorage

import (
	"os"
	"strings"
	"sync"
	"testing"
	"time"
)

// Values generated by the oracle (SECRET_KEY_BASE of test/oracle/oracle.env).
func TestVerifierMatchesRails(t *testing.T) {
	env, err := os.ReadFile("../../test/oracle/oracle.env")
	if err != nil {
		t.Fatal(err)
	}
	for _, line := range strings.Split(string(env), "\n") {
		if v, ok := strings.CutPrefix(line, "SECRET_KEY_BASE="); ok {
			t.Setenv("SECRET_KEY_BASE", v)
		}
	}
	secretOnce = sync.Once{}
	if got := Generate(123, "blob_id"); got != "eyJfcmFpbHMiOnsiZGF0YSI6MTIzLCJwdXIiOiJibG9iX2lkIn19--c21375b8c58b95c2854dab241910b4e9fd64d08c" {
		t.Fatalf("generate: %s", got)
	}
	if got := AttachableSGID(1); got != "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2VzdGV2YW8tYXBpL0FjdGl2ZVN0b3JhZ2U6OkJsb2IvMT9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ==--84b8e41abfae1a28f4540d5db72fbc52914c6d74" {
		t.Fatalf("sgid: %s", got)
	}
	now := time.Date(2026, 9, 24, 6, 49, 0, 0, time.UTC)
	for name, msg := range map[string]string{
		"current":  "eyJfcmFpbHMiOnsiZGF0YSI6MTIzLCJwdXIiOiJibG9iX2lkIn19--c21375b8c58b95c2854dab241910b4e9fd64d08c",
		"expiring": "eyJfcmFpbHMiOnsiZGF0YSI6MTIzLCJleHAiOiIyMDI2LTA5LTI0VDA2OjQ5OjU5LjUyM1oiLCJwdXIiOiJibG9iX2lkIn19--ecad56e1ad04d3392f34e21d591addc64f8179a5",
		"marshal":  "BAh7BkkiC19yYWlscwY6BkVUewdJIglkYXRhBjsAVGkBe0kiCHB1cgY7AFRJIgxibG9iX2lkBjsARg==--425f06d8b7dd2d793c42268d32cbd7cd7dbaf8b2",
	} {
		if id, ok := Verified(msg, "blob_id", now); !ok || id != 123 {
			t.Errorf("%s: %d %v", name, id, ok)
		}
	}
	if _, ok := Verified("eyJfcmFpbHMiOnsiZGF0YSI6MTIzLCJleHAiOiIyMDI2LTA5LTI0VDA2OjQ5OjU5LjUyM1oiLCJwdXIiOiJibG9iX2lkIn19--ecad56e1ad04d3392f34e21d591addc64f8179a5", "blob_id", now.Add(time.Hour)); ok {
		t.Error("expired message verified")
	}
	if _, ok := Verified("eyJfcmFpbHMiOnsiZGF0YSI6MTIzLCJwdXIiOiJibG9iX2lkIn19--c21375b8c58b95c2854dab241910b4e9fd64d08d", "blob_id", now); ok {
		t.Error("tampered message verified")
	}
}
