package rb

import (
	"bufio"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"os"
	"testing"
	"time"
)

// testdata/timeparse.jsonl.gz is generated by tools/golden/timeparse_corpus.rb
// under TZ=UTC and TZ=America/New_York.
func TestTimeParseMatchesRuby(t *testing.T) {
	f, err := os.Open("testdata/timeparse.jsonl.gz")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		t.Fatal(err)
	}
	now := time.Unix(1790251200, 123456789)
	sc := bufio.NewScanner(gz)
	n, bad := 0, 0
	for sc.Scan() {
		var c struct{ S, R, TZ string }
		if err := json.Unmarshal(sc.Bytes(), &c); err != nil {
			t.Fatal(err)
		}
		loc, err := time.LoadLocation(c.TZ)
		if err != nil {
			t.Fatal(err)
		}
		n++
		var got string
		if tm, err := TimeParse(c.S, now, loc); err != nil {
			got = "ERR:" + err.Error()
		} else {
			got = fmt.Sprintf("%d.%09d", tm.Unix(), tm.Nanosecond())
		}
		if got != c.R {
			bad++
			if bad <= 40 {
				t.Errorf("[%s] Time.parse(%q): ruby %s go %s", c.TZ, c.S, c.R, got)
			}
		}
	}
	t.Logf("%d cases, %d mismatches", n, bad)
}
