// Package audio ports the request-time half of the Rails narration pipeline
// (app/services/audio): which lines of an office are spoken, the text sent to
// the speech provider, the deterministic clip key, and the track the app plays
// built from clips already in the catalogue. Generation itself (the provider
// HTTP calls) runs in the Rails jobs and is not part of a request.
package audio

import (
	"math"
	"os"
	"strconv"
	"strings"

	"github.com/dodopok/estevao-api-go/internal/rb"
)

// Provider ports Audio::Providers::Base and its three backends: the knobs that
// change the generated bytes and so address a clip.
type Provider struct {
	Name     string
	Model    string
	Voice    string
	Language string
	Speed    float64
	// Instructions is the steering prompt in the cache signature ("" when the
	// model ignores it).
	Instructions          string
	SplitTerminalResponse bool
	// ShortInputMax is Google's short_input_max_characters; 0 means every
	// input is addressed alike.
	ShortInputMax     int
	shortInstructions string
}

// MaxInputCharacters ports max_input_characters.
func (p *Provider) MaxInputCharacters() int { return DefaultMaxCharacters }

// CacheSignature ports cache_signature(normalized). A nil text is the
// signature of every input outside the short class.
func (p *Provider) CacheSignature(normalized *string) string {
	base := p.Name + " " + p.Model + " " + rb.FloatToS(p.Speed) + " " + p.Language + " " + p.Instructions
	if p.ShortInputMax == 0 || normalized == nil || rubyLen(strings.TrimSpace(*normalized)) > p.ShortInputMax {
		return base
	}
	return base + " short-input " + p.shortInstructions
}

// ArgumentError mirrors the Ruby exception raised for an unknown provider.
type ArgumentError struct{ Message string }

func (e *ArgumentError) Error() string { return e.Message }

// Current ports Audio::Providers.current(language:). language is nil when the
// Ruby caller passes nil (the backend then reads its own env default).
func Current(language *string) *Provider {
	name := os.Getenv("AUDIO_TTS_PROVIDER")
	if _, ok := os.LookupEnv("AUDIO_TTS_PROVIDER"); !ok {
		name = "openai"
	}
	return Build(name, language)
}

// Build ports Audio::Providers.build.
func Build(name string, language *string) *Provider {
	switch strings.ToLower(name) {
	case "openai":
		return openAI(language)
	case "elevenlabs":
		return elevenLabs(language)
	case "google":
		return google(language)
	}
	panic(&rb.RubyError{Class: "ArgumentError",
		Message: "unknown audio provider: " + name + " (known: openai, elevenlabs, google)"})
}

func envOr(key, fallback string) string {
	if v, ok := os.LookupEnv(key); ok {
		return v
	}
	return fallback
}

// languageArg ports `language || ENV[key]` followed by
// `value.to_s.strip.presence || "pt-BR"`.
func languageArg(language *string, envKey string) string {
	var v string
	if language != nil {
		v = *language
	} else {
		v = os.Getenv(envKey)
	}
	v = strings.TrimSpace(v)
	if v == "" {
		return "pt-BR"
	}
	return v
}

// envFloat ports Float(ENV.fetch(key, default)).clamp(lo, hi) with the
// ArgumentError fallback to the default.
func envFloat(key string, def, lo, hi float64) float64 {
	raw, ok := os.LookupEnv(key)
	if !ok {
		return math.Min(math.Max(def, lo), hi)
	}
	f, ok := rubyFloat(raw)
	if !ok {
		return def
	}
	return math.Min(math.Max(f, lo), hi)
}

// rubyFloat ports Kernel#Float for a String: surrounding whitespace and
// single underscores between digits are allowed, anything else raises.
func rubyFloat(s string) (float64, bool) {
	s = strings.TrimSpace(s)
	if s == "" || strings.HasPrefix(s, "_") || strings.HasSuffix(s, "_") || strings.Contains(s, "__") {
		return 0, false
	}
	s = strings.ReplaceAll(s, "_", "")
	if strings.HasSuffix(s, ".") || strings.HasPrefix(s, ".") || strings.Contains(s, "._") {
		return 0, false
	}
	low := strings.ToLower(s)
	if strings.Contains(low, "inf") || strings.Contains(low, "nan") || strings.HasPrefix(strings.TrimLeft(low, "+-"), "0x") {
		return 0, false
	}
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 0, false
	}
	return f, true
}

// byLanguage ports hash.fetch(language, hash.fetch(language.split("-", 2).first, fallback)).
func byLanguage(m map[string]string, language, fallback string) string {
	if v, ok := m[language]; ok {
		return v
	}
	if v, ok := m[strings.SplitN(language, "-", 2)[0]]; ok {
		return v
	}
	return fallback
}

func openAI(language *string) *Provider {
	p := &Provider{Name: "openai", SplitTerminalResponse: true}
	p.Language = languageArg(language, "OPENAI_TTS_LANGUAGE")
	p.Model = envOr("OPENAI_TTS_MODEL", "gpt-4o-mini-tts")
	p.Voice = envOr("OPENAI_TTS_VOICE", "cedar")
	p.Speed = envFloat("OPENAI_TTS_SPEED", 1.0, 0.25, 4.0)
	if p.Model != "tts-1" && p.Model != "tts-1-hd" {
		if v := os.Getenv("OPENAI_TTS_INSTRUCTIONS"); !rb.BlankString(v) {
			p.Instructions = v
		} else {
			p.Instructions = byLanguage(openAIInstructions, p.Language, openAIInstructions["pt-BR"])
		}
	}
	return p
}

func elevenLabs(language *string) *Provider {
	p := &Provider{Name: "elevenlabs", Model: elevenLabsModelID, Speed: 1.0}
	p.Language = "pt-BR"
	if language != nil && *language != "" {
		p.Language = *language
	}
	p.Voice = envOr("ELEVENLABS_TTS_VOICE", "male_1")
	return p
}

func google(language *string) *Provider {
	p := &Provider{Name: "google"}
	p.Language = languageArg(language, "GOOGLE_TTS_LANGUAGE")
	p.Model = envOr("GOOGLE_TTS_MODEL", "gemini-2.5-flash-tts")
	p.Voice = envOr("GOOGLE_TTS_VOICE", "Orus")
	p.Speed = envFloat("GOOGLE_TTS_SPEED", 1.0, 0.25, 2.0)
	if v := os.Getenv("GOOGLE_TTS_INSTRUCTIONS"); !rb.BlankString(v) {
		p.Instructions = v
	} else {
		p.Instructions = byLanguage(googleInstructions, p.Language, googleInstructions["pt-BR"])
	}
	p.ShortInputMax = 120
	if raw, ok := os.LookupEnv("GOOGLE_TTS_SHORT_INPUT_MAX_CHARACTERS"); ok {
		if n, ok := rubyInteger(raw); ok && n > 0 {
			p.ShortInputMax = n
		}
	}
	p.shortInstructions = byLanguage(googleShortInstructions, p.Language, "")
	return p
}

// rubyInteger ports Kernel#Integer for a decimal String.
func rubyInteger(s string) (int, bool) {
	s = strings.TrimSpace(s)
	if s == "" || strings.HasPrefix(s, "_") || strings.HasSuffix(s, "_") || strings.Contains(s, "__") {
		return 0, false
	}
	n, err := strconv.ParseInt(strings.ReplaceAll(s, "_", ""), 10, 64)
	if err != nil {
		return 0, false
	}
	return int(n), true
}

// rubyLen is String#length (characters, not bytes).
func rubyLen(s string) int { return len([]rune(s)) }
